version: 0.0
os: linux
files:
  - source: /
    destination: /opt/sample
    overwrite: true
permissions:
  - object: /opt/sample/script
    pattern: "*.sh"
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: script/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: script/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: script/app_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: script/app_stop.sh
      timeout: 300
      runas: root
